// <auto-generated />
namespace EFCF.Estudiantes.LarghiF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class EstadoDelEstudiante : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EstadoDelEstudiante));
        
        string IMigrationMetadata.Id
        {
            get { return "202204190245416_EstadoDelEstudiante"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
